FROM java:8
VOLUME /tmp
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ADD docker/wrapper.sh wrapper.sh
RUN bash -c 'chmod +x /wrapper.sh'
ENV PARENTS_SERVICE_PORT=$PARENTS_SERVICE_PORT
ENV PARENTS_DB_HOST=$PARENTS_DB_HOST
ENV PARENTS_DB_PORT=$PARENTS_DB_PORT
ENV PARENTS_DB_NAME=$PARENTS_DB_NAME
ENV PARENTS_DB_USER=$PARENTS_DB_USER
ENV PARENTS_DB_PASSWORD=$PARENTS_DB_PASSWORD
ENTRYPOINT ["/bin/bash", "/wrapper.sh"]